# Site settings
title: resume
SEOTitle: 郭成的简历 | Roger Resume
url: "http://nankaigc.github.io/resume"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/nankaigc/nankaigc.github.io.git" # you code repository
